### ISSUE TITLE
missing git tag 1.10

### ISSUE THREAD

**Issue by anthraxx** [python-trio/async_generator#24]
Hi,

On pypi the 1.10 is already published. it would be nice to have a corresponding git commit available via a pushed git tag.
Can you please tag and push 1.10 to github?
cheers

**Comment by njsmith** [comment]
The good news is this is fixed. The bad news is I feel very silly :-). (Apparently I have been pushing the tags to my fork, rather than the main repo...)

**Comment by anthraxx** [comment]
No worries, happens 😊 thanks
