### ISSUE TITLE
appveyor coverage isn't working

### ISSUE THREAD

**Issue by njsmith** [python-trio/async_generator#6]
should probably figure out why and fix it at some point

**Comment by pquentin** [comment]
I think this one is now fixed!

**Comment by njsmith** [comment]
Doesn't look like it -- here's a log from the last appveyor run: https://ci.appveyor.com/project/njsmith/async-generator/build/1.0.20/job/oqwgv9mtav5blwmv

and if you scroll down to the bottom, pytest reports 2.1% coverage, and there's a line "Coverage.py warning: No data was collected. (no-data-collected)"

**Comment by pquentin** [comment]
Sorry, I misread the issue as "appveyor is not working". Thanks for the detailed explanation.

**Comment by njsmith** [comment]
Fixed by #9.
